<?php

/**
 * @file
 * Display Suite test module.
 */

/**
 * Implements hook_install().
 */
function ds_test_install() {
  variable_set('ds_extras_region_to_block', TRUE);
  variable_set('ds_extras_switch_view_mode', TRUE);
}

/**
 * Implements hook_ds_fields_info().
 */
function ds_test_ds_fields_info($entity_type, $bundle, $view_mode) {
  if ($entity_type == 'node') {
    $fields['node']['ds_test_field'] = array(
      'title' => t('Test code field from hook'),
      'field_type' => DS_FIELD_TYPE_FUNCTION,
      'function' => 'dstest_render_test_field',
    );
    $fields['node']['ds_test_field_2'] = array(
      'title' => t('Test code field from hook 2'),
      'field_type' => DS_FIELD_TYPE_FUNCTION,
      'function' => 'dstest_render_test_field',
    );

    return $fields;
  }
}

function dstest_render_test_field($field) {
  return 'Test code field on node ' . $field['entity']->nid;
}

/**
 * Implements hook_ds_fields_info_alter().
 */
function ds_test_ds_fields_info_alter(&$fields) {
  if (isset($fields['ds_test_field_2'])) {
    $fields['ds_test_field_2']['title'] = 'Field altered';
  }
}

/**
 * Implements hook_ds_layouts().
 */
function ds_extras_ds_layout_info() {
  $path = drupal_get_path('module', 'ds_test');
  $layouts = array(
    'dstest_1col' => array(
      'label' => t('Test One column'),
      'path' => $path . '/dstest_1col',
      'regions' => array(
        'ds_content' => t('Content'),
      ),
    ),
    'dstest_2col' => array(
      'label' => t('Test Two column'),
      'path' => $path . '/dstest_2col',
      'regions' => array(
        'left' => t('Left'),
        'right' => t('Right')
      ),
      'css' => TRUE,
    ),
  );

  return $layouts;
}
